name: potato_apps
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: 6.1.0
  fluttertoast: ^8.2.4
  syncfusion_flutter_charts: ^20.3.61
  toggle_switch: ^2.3.0
  image_picker: ^0.8.4+2
  stroke_text: any
  firebase_database: ^10.4.9
  intl: ^0.17.0
  http: ^1.2.0
  firebase_storage: ^11.6.9
  flutter_native_image: ^0.0.6+1
  flutter_image_compress: 2.2.0
  awesome_snackbar_content: ^0.1.1
  lottie: ^3.1.2
  firebase_messaging: ^14.7.19
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  google_sign_in: ^6.2.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.5

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png" # Pastikan ini adalah file PNG dengan transparansi
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "transparent" # Web mendukung warna transparan
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon_home.png
    - assets/icon_detect.png
    - assets/icon_history.png
    - assets/icon_profile.png
    - assets/animations/
