name: potato_apps
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: 6.1.0
  fluttertoast: ^8.2.4
  syncfusion_flutter_charts: ^20.3.61
  toggle_switch: ^2.3.0
  image_picker: ^0.8.4+2
  stroke_text: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  google_sign_in: ^6.2.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.5

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon_home.png
    - assets/icon_detect.png
    - assets/icon_history.png
    - assets/icon_profile.png
